### ISSUE TITLE
404 errors from API calls

### ISSUE THREAD

**Issue by maxt3r** [Irio/ruby-tmdb#10]
I'm getting a 404 error from every API call I'm trying to make. For example this code:
`@movie = TmdbMovie.find(:title => "Iron Man", :limit => 1)`

returns this: 
`RuntimeError: Tmdb API returned status code '404' for URL: 'http://api.themoviedb.org/3/search/movie'`

Maybe there is something wrong on my machine, but I saw official API requires `Accept: application/json` header to be set and I coudn't find it in your source codes. Could it be the reason?

**Comment by maxt3r** [comment]
I've cloned this repo and ran tests, they all pass, so there must be something with my rails app. I've set up the API key and the default language in a inititalizers, but all API calls always return 404. Any help?

**Comment by Irio** [comment]
Hi @maxt3r,

I just tested with `0.3.4` and edge code from master branch and couldn't reproduce your error.

``` ruby
require 'ruby-tmdb3'
Tmdb.api_key = 'my-valid-api-key'
@movie = TmdbMovie.find(:title => "Iron Man", :limit => 1)
# => #<PatchedOpenStruct adult=false, backdrop_path="/ZQixhAZx6fH1VNafFXsqa1B8QI.jpg"...
```

Problably it was temporary instability with Tmdb itself or your api key is invalid or was not set right.

``` ruby
require 'ruby-tmdb3'
Tmdb.api_key = 'invalid-api-key'
 @movie = TmdbMovie.find(:title => "Iron Man", :limit => 1)
# => RuntimeError: Tmdb API returned status code '404' for URL: 'http://api.themoviedb.org/3/search/movie'
# => from /Users/irio/.rvm/gems/ruby-1.9.3-p327@global/gems/ruby-tmdb3-0.3.4/lib/ruby-tmdb3/tmdb.rb:84:in `api_call'
```

**Comment by maxt3r** [comment]
I was debugging it yesterday and it turned out I had an incorrect API key. Maybe we should add `response.body` to the error output? Would've saved me a day.

**Comment by Irio** [comment]
I think is more a problem with the API itself, because 404 status its clear: this resource was not found. This could be reported to them, asking to change this behavior to a [401](http://httpstatus.es/401).

**Comment by maxt3r** [comment]
True. But I still think `response.body` could be useful. I can add it and fill a proper pull request, what do you think?

**Comment by Irio** [comment]
Sure. It's better discuss this in a dedicated pull request.
