### ISSUE TITLE
default_lang is not passed to api_call

### ISSUE THREAD

**Issue by fguillen** [Irio/ruby-tmdb#2]
I know you have this already solved: https://github.com/Irio/ruby-tmdb/commit/04ecfc6892ad9acf9db9c551bc04da63d034e062

Just asking for release a new version with this fix.

**Comment by Irio** [comment]
Thanks for the report, @fguillen. I wrote this commit a few days ago but wasn't planning releasing a new version just with this, since don't received any issue related.

You can update to 0.3.2 now.

**Comment by fguillen** [comment]
Sorry for answer so late, just let you know that I used the new version of the gem as soon as you released it!. Thanks for your job.

**Comment by Irio** [comment]
Thanks for your contribution too, feel free to do them more. :)
